use crate::contracts::{
    MCP_ACTIVITY_ROLLUPS_V1, MCP_BUILD_INFO_V1, MCP_CLOSE_GOVERNANCE_LANE_V1,
    MCP_CREATE_GOVERNANCE_LANE_V1, MCP_DATA_RISK_V1, MCP_DELETE_PROJECT_V1,
    MCP_GET_GOVERNANCE_STATE_V1, MCP_GLOBAL_CONFIG_V1, MCP_GUIDANCE_V1, MCP_LIST_PROJECTS_V1,
    MCP_ORPHAN_DELETION_PLAN_V1, MCP_ORPHAN_SCAN_V1, MCP_PROJECT_CONFIG_V1,
    MCP_RECORD_VERIFICATION_V1, MCP_REGISTER_PROJECT_V1, MCP_RUN_VERIFICATION_V1,
    MCP_SNAPSHOT_COMPARE_V1, MCP_SNAPSHOT_V1, MCP_START_MONITOR_V1, MCP_STATS_V1,
    MCP_STOP_MONITOR_V1, MCP_TIME_WINDOW_REPORT_V1, MCP_UNUSED_FILES_V1,
    MCP_UPSERT_GOVERNANCE_NODE_V1, MCP_USAGE_TRENDS_V1, MCP_VERIFICATION_STATUS_V1,
    MCP_WORKSPACE_DATA_RISK_V1,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct McpToolSpec {
    pub(crate) name: &'static str,
    pub(crate) contract: &'static str,
    pub(crate) params_type: Option<&'static str>,
    pub(crate) payload_builder: &'static str,
    pub(crate) handler_module: &'static str,
    pub(crate) handler: &'static str,
    pub(crate) test_owner: &'static str,
}

pub(crate) const MCP_TOOL_INVENTORY: &[McpToolSpec] = &[
    McpToolSpec {
        name: "get_guidance",
        contract: MCP_GUIDANCE_V1,
        params_type: Some("GuidanceParams"),
        payload_builder: "agent_guidance_payload",
        handler_module: "guidance_handlers",
        handler: "handle_get_guidance",
        test_owner: "mcp::tests::guidance_basics",
    },
    McpToolSpec {
        name: "get_global_config",
        contract: MCP_GLOBAL_CONFIG_V1,
        params_type: None,
        payload_builder: "global_config_payload",
        handler_module: "config_handlers",
        handler: "handle_get_global_config",
        test_owner: "mcp::tests::payload_contracts::config_payloads",
    },
    McpToolSpec {
        name: "get_build_info",
        contract: MCP_BUILD_INFO_V1,
        params_type: None,
        payload_builder: "build_info_payload",
        handler_module: "config_handlers",
        handler: "handle_get_build_info",
        test_owner: "mcp::tests::payload_contracts::config_payloads",
    },
    McpToolSpec {
        name: "get_project_config",
        contract: MCP_PROJECT_CONFIG_V1,
        params_type: Some("ProjectIdParams"),
        payload_builder: "project_config_payload",
        handler_module: "config_handlers",
        handler: "handle_get_project_config",
        test_owner: "mcp::tests::payload_contracts::config_payloads",
    },
    McpToolSpec {
        name: "register_project",
        contract: MCP_REGISTER_PROJECT_V1,
        params_type: Some("RegisterProjectParams"),
        payload_builder: "register_project_payload",
        handler_module: "project_handlers",
        handler: "handle_register_project",
        test_owner: "mcp::tests::payload_contracts::project_payloads",
    },
    McpToolSpec {
        name: "take_snapshot",
        contract: MCP_SNAPSHOT_V1,
        params_type: Some("ProjectIdParams"),
        payload_builder: "snapshot_payload",
        handler_module: "project_handlers",
        handler: "handle_take_snapshot",
        test_owner: "mcp::tests::payload_contracts::analysis_payloads",
    },
    McpToolSpec {
        name: "start_monitor",
        contract: MCP_START_MONITOR_V1,
        params_type: Some("ProjectIdParams"),
        payload_builder: "start_monitor_payload",
        handler_module: "project_handlers",
        handler: "handle_start_monitor",
        test_owner: "mcp::tests::payload_contracts::project_payloads",
    },
    McpToolSpec {
        name: "stop_monitor",
        contract: MCP_STOP_MONITOR_V1,
        params_type: Some("ProjectIdParams"),
        payload_builder: "stop_monitor_payload",
        handler_module: "project_handlers",
        handler: "handle_stop_monitor",
        test_owner: "mcp::tests::payload_contracts::project_payloads",
    },
    McpToolSpec {
        name: "get_stats",
        contract: MCP_STATS_V1,
        params_type: Some("ObservationRowsParams"),
        payload_builder: "stats_payload",
        handler_module: "analysis_handlers",
        handler: "handle_get_stats",
        test_owner: "mcp::tests::payload_contracts::analysis_payloads",
    },
    McpToolSpec {
        name: "get_unused_files",
        contract: MCP_UNUSED_FILES_V1,
        params_type: Some("ObservationRowsParams"),
        payload_builder: "unused_files_payload",
        handler_module: "analysis_handlers",
        handler: "handle_get_unused_files",
        test_owner: "mcp::tests::payload_contracts::analysis_payloads",
    },
    McpToolSpec {
        name: "get_time_window_report",
        contract: MCP_TIME_WINDOW_REPORT_V1,
        params_type: Some("TimeWindowReportParams"),
        payload_builder: "time_window_report_payload",
        handler_module: "analysis_handlers",
        handler: "handle_get_time_window_report",
        test_owner: "mcp::tests::payload_contracts::analysis_payloads",
    },
    McpToolSpec {
        name: "compare_snapshots",
        contract: MCP_SNAPSHOT_COMPARE_V1,
        params_type: Some("CompareSnapshotsParams"),
        payload_builder: "snapshot_compare_payload",
        handler_module: "analysis_handlers",
        handler: "handle_compare_snapshots",
        test_owner: "mcp::tests::payload_contracts::analysis_payloads",
    },
    McpToolSpec {
        name: "get_usage_trends",
        contract: MCP_USAGE_TRENDS_V1,
        params_type: Some("UsageTrendParams"),
        payload_builder: "usage_trends_payload",
        handler_module: "analysis_handlers",
        handler: "handle_get_usage_trends",
        test_owner: "mcp::tests::payload_contracts::analysis_payloads",
    },
    McpToolSpec {
        name: "get_activity_rollups",
        contract: MCP_ACTIVITY_ROLLUPS_V1,
        params_type: Some("ActivityRollupParams"),
        payload_builder: "activity_rollups_payload",
        handler_module: "analysis_handlers",
        handler: "handle_get_activity_rollups",
        test_owner: "mcp::tests::payload_contracts::analysis_payloads",
    },
    McpToolSpec {
        name: "get_verification_status",
        contract: MCP_VERIFICATION_STATUS_V1,
        params_type: Some("ProjectIdParams"),
        payload_builder: "verification_status_payload",
        handler_module: "verification_handlers",
        handler: "handle_get_verification_status",
        test_owner: "mcp::tests::payload_contracts::verification_payloads",
    },
    McpToolSpec {
        name: "record_verification_result",
        contract: MCP_RECORD_VERIFICATION_V1,
        params_type: Some("RecordVerificationParams"),
        payload_builder: "record_verification_payload",
        handler_module: "verification_handlers",
        handler: "handle_record_verification_result",
        test_owner: "mcp::tests::payload_contracts::verification_payloads",
    },
    McpToolSpec {
        name: "run_verification_command",
        contract: MCP_RUN_VERIFICATION_V1,
        params_type: Some("ExecuteVerificationParams"),
        payload_builder: "run_verification_payload",
        handler_module: "verification_handlers",
        handler: "handle_run_verification_command",
        test_owner: "mcp::tests::payload_contracts::verification_payloads",
    },
    McpToolSpec {
        name: "scan_orphans",
        contract: MCP_ORPHAN_SCAN_V1,
        params_type: Some("ScanOrphansParams"),
        payload_builder: "orphan_scan_payload",
        handler_module: "orphan_handlers",
        handler: "handle_scan_orphans",
        test_owner: "mcp::tests::payload_contracts::orphan_payloads",
    },
    McpToolSpec {
        name: "verify_deletion_plan",
        contract: MCP_ORPHAN_DELETION_PLAN_V1,
        params_type: Some("VerifyDeletionPlanParams"),
        payload_builder: "orphan_deletion_plan_payload",
        handler_module: "orphan_handlers",
        handler: "handle_verify_deletion_plan",
        test_owner: "mcp::tests::payload_contracts::orphan_payloads",
    },
    McpToolSpec {
        name: "get_data_risk_candidates",
        contract: MCP_DATA_RISK_V1,
        params_type: Some("DataRiskParams"),
        payload_builder: "project_data_risk_payload",
        handler_module: "risk_handlers",
        handler: "handle_get_data_risk_candidates",
        test_owner: "mcp::tests::data_risk_cases",
    },
    McpToolSpec {
        name: "get_workspace_data_risk_overview",
        contract: MCP_WORKSPACE_DATA_RISK_V1,
        params_type: Some("WorkspaceDataRiskParams"),
        payload_builder: "workspace_data_risk_payload",
        handler_module: "risk_handlers",
        handler: "handle_get_workspace_data_risk_overview",
        test_owner: "mcp::tests::data_risk_cases",
    },
    McpToolSpec {
        name: "list_projects",
        contract: MCP_LIST_PROJECTS_V1,
        params_type: None,
        payload_builder: "list_projects_payload",
        handler_module: "project_handlers",
        handler: "handle_list_projects",
        test_owner: "mcp::tests::payload_contracts::project_payloads",
    },
    McpToolSpec {
        name: "delete_project",
        contract: MCP_DELETE_PROJECT_V1,
        params_type: Some("ProjectIdParams"),
        payload_builder: "delete_project_payload",
        handler_module: "project_handlers",
        handler: "handle_delete_project",
        test_owner: "mcp::tests::payload_contracts::project_payloads",
    },
    McpToolSpec {
        name: "create_governance_lane",
        contract: MCP_CREATE_GOVERNANCE_LANE_V1,
        params_type: Some("CreateGovernanceLaneParams"),
        payload_builder: "create_governance_lane_payload",
        handler_module: "governance_handlers",
        handler: "handle_create_governance_lane",
        test_owner: "mcp::tests::payload_contracts::governance_payloads",
    },
    McpToolSpec {
        name: "upsert_governance_node",
        contract: MCP_UPSERT_GOVERNANCE_NODE_V1,
        params_type: Some("UpsertGovernanceNodeParams"),
        payload_builder: "upsert_governance_node_payload",
        handler_module: "governance_handlers",
        handler: "handle_upsert_governance_node",
        test_owner: "mcp::tests::payload_contracts::governance_payloads",
    },
    McpToolSpec {
        name: "get_governance_state",
        contract: MCP_GET_GOVERNANCE_STATE_V1,
        params_type: Some("GetGovernanceStateParams"),
        payload_builder: "get_governance_state_payload",
        handler_module: "governance_handlers",
        handler: "handle_get_governance_state",
        test_owner: "mcp::tests::payload_contracts::governance_payloads",
    },
    McpToolSpec {
        name: "close_governance_lane",
        contract: MCP_CLOSE_GOVERNANCE_LANE_V1,
        params_type: Some("CloseGovernanceLaneParams"),
        payload_builder: "close_governance_lane_payload",
        handler_module: "governance_handlers",
        handler: "handle_close_governance_lane",
        test_owner: "mcp::tests::payload_contracts::governance_payloads",
    },
];

pub(crate) fn mcp_tool_inventory() -> &'static [McpToolSpec] {
    MCP_TOOL_INVENTORY
}

#[cfg(test)]
mod tests;
